#
#
# Based on https://github.com/felixrieseberg/travis-jekyll-git/tree/4a8f6d505a7219b2d50e4d0b64f3ee4774016f5b
#
#
language: ruby
rvm:
  - 2.5

install: 
 - bundle update
 - bundle show
 - bundle install
 - gem install html-proofer jekyll-sitemap
script: 
 - . scripts/ci/build.sh
 - /bin/ls -altr _site
 - cat ./_site/join.html

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
  - add-travis

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# deploy:
#   skip_cleanup: true
#   provider: script
#   script: scripts/deploy.sh
#   on:
#     branch: gh-pages
