title: US-RSE
author: us-rse
email: 
description: > # this means to ignore newlines until "baseurl:"
  The community of Research Software Engineers 
  from US universities, laboratories, knowledge institutes, companies and
  other relevant organizations for sharing knowledge, organizing
  meetings and raising awareness for the scientific recognition of research software.
twitter_username:
github_username:  usrse
slack_channel: usrse.slack.com

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - community.md
 - join.md
 - communication.md

# Build settings
markdown: kramdown
theme: minima
