# Site Settings
lang: en

title: US-RSE Association
description: Community of Research Software Engineers

url: ""
baseurl: "/usrse.github.io"  # for testing, also check .circleci/circle_urls.sh
title-img: /assets/img/99design-logo-transparent.png  # baseurl will be prepended
twitter-img: /assets/img/99design-logo-transparent.png  # url + baseurl will be prepended
banner: /assets/img/99design-logo-transparent.png
icon: /assets/img/99design-logo-transparent.png

email: contact@us-rse.org
permalink: /:year-:month-:day-:title/

favicon: /assets/img/favicon.ico
#hide_share_buttons: true
#theme_color: '#eeeeee'
fixed_navbar: top

paginate: 5
paginate_path: "/news/page:num/"

excerpt_length: 500

hero_line_one: The United States Research Software Engineer Assocation
hero_line_two: A community of people who make research software happen.

# social media
twitter: us_rse
github_org: USRSE
linkedin: company/us-rse/

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

exclude: 
  - Gemfile
  - Gemfile.lock
  - vendor

livereload: true

google_analytics: "UA-133428825-1"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true
  - 
    scope:
      path: "_events"
      type: "events"
    values:
      layout: event


markdown: kramdown
highlighter: rouge

# Collections
collections:
  events:
    output: true
    permalink: /:collection/:path/
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
