name: Check Spelling and URLs

on: [pull_request]

# Kill concurrent jobs from the same PR/branch - only one will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check Spelling
      uses: crate-ci/typos@master # we should really incorporate all new changes
      with:
        files: ./_posts ./pages ./README.md
        config: ./.github/workflows/typo_config.toml

    - name: URLs-checker

      uses: urlstechie/urlchecker-action@0.0.34
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.yml

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # More verbose summary at the end of a run
        verbose: true

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3

        # Google Forms is having enormous timeouts
        timeout: 10

        # Exclude these patterns from the checker
        exclude_patterns: "supercomputing.org,\
          https://pace.gatech.edu,\
          https://www.linkedin.com,\
          jobs.colorado.edu,zoom.us,\
          danielskatz.org,\
          usrse.github.io.wiki.git,\
          ornl.gov,\
          jobs.bnl.gov,\
          https://www.rd-alliance.org/,\
          https://uwhires.admin.washington.edu/,\
          https://careers.umich.edu/,\
          https://twitter.com/us_rse,\
          https://twitter.com/us_rse/status/1447622175133945860,\
          https://twitter.com/iancosden/status/1122937311644323841,\
          https://bitcon.blacksintechnology.net/,\
          https://travel.usnews.com/features/top-pride-parades-and-celebrations-in-the-us,\
          https://family.20thcenturystudios.com/movies/hidden-figures,\
          https://www.usatoday.com/story/money/2023/06/07/silicon-valley-tech-black-history-roy-clay/70262081007/"

        # Exclude these files from the checker
        exclude_files: "README.md,\
          docs/events.md,\
          docs/tests_ci.md,\
          docs/local_previews.md,\
          SocialNetworks.yml,\
          map.yml,\
          _config.yml,\
          tests/test_,\
          .github/workflows,\
          _posts/newsletters/"
