[files]
extend-exclude = [
    ".git/",
    ".github/workflows/typo_config.toml",
    "assets/js/*.min.*",
    "pages/feeds/*.xml"
]
ignore-hidden = true
[default]
extend-ignore-re = [
    "Brain tailoRed stImulation protocoL",
    "Vas Vasiliadis",
    "Nam Pho",
    "SLAC",
    "Paul Hsi",
    "NWO",
    "ND",
    "AAS",
    "Villegas",
    "Wil",
    "Lok"
]
