name: Check URLs

on: [pull_request]

jobs:
  urlcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: URLs-checker
      uses: urlstechie/urlchecker-action@update/version-0.0.20
      with:
        # A comma-separated list of file types to cover in the URL checks
        file_types: .md,.py,.yml

        # Choose whether to include file with no URLs in the prints.
        print_all: false

        # How many times to retry a failed request (defaults to 1)
        retry_count: 3

        # Google Forms is having enormous timeouts
        timeout: 10

        # White listed patterns (seem to have SSL issues but work in browser)
        white_listed_patterns: sc19.supercomputing.org,https://pace.gatech.edu,https://www.linkedin.com

        # White list the following files
        white_listed_files: README.md,SocialNetworks.yml,_config.yml,tests/test_,.github/workflows,_posts/newsletters/
